---
- hosts: testservers
  remote_user: root

  tasks:
    - name : Installing Apache
    yum:
      name: httpd
      state: installed

    - name : Enabling httpd service and start the service  
      service:
        name: httpd
        enabled: yes
        state: started

    - name: Install MySQL DB Community edition 
      yum:
        name: 
          - maraidb-server
          - maraidb
          state: latest

    - name : Start the MySQL service 
      service:
        name: mysqld 
        enabled: yes
        state: started

    - name: Installing PHP
      yum:
        name:
          - php
          - php-mysql
        state: latest

    - name : Copying your php file in the /opt/homebrew/var/www/html
      copy:
        src: /Documents/Cours/DevOps/lamp-ansible/index.php
        dest: /opt/homebrew/var/www/html/index.php


